version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    command: ["/app/entrypoint.sh"]  # Custom entrypoint script

volumes:
  db_data:
