services:
  app:
    build: .
    container_name: app-container
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    networks:
      - app-network    # Use the existing network
    environment:
      - DB_HOST=mysql-container    # Use the container name of the standalone MySQL
      - DB_USER=root
      - DB_PASSWORD=cowabunga
      - DB_NAME=mydb
      - AWS_DEFAULT_REGION=us-east-1
    restart: unless-stopped
    command: ["/app/entrypoint.sh"]
 
networks:
  app-network:
    external: true    # Use existing network instead of creating new one